server:
  port: 8888

spring:
  cloud:
    config:
      discovery:
        enabled: false
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/ZilvinasVysniauskas/config-repo/
          searchPaths: licensingservice,organizationservice
          default-label: master
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
